name: polartoolkit-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - nbgitpuller
  - polartoolkit=0.3.3
  # interactive
  - geoviews
  - cartopy
  - ipyleaflet
  - ipython
  # viz
  - seaborn
