name: polartoolkit-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - polartoolkit=0.3.3
  # interactive
  - geoviews=1.12.0
  - cartopy=0.23.0
  - ipyleaflet=0.19.0
  - ipython=8.22.2
  # viz
  - seaborn=0.13.2
