name: polartoolkit-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - nbgitpuller
  - pygmt=0.13
  - geopandas=0.14
  # - cartopy=0.23
  # interactive
  # - geoviews
  # - ipyleaflet=0.19
  # - ipython
  # # viz
  # - seaborn
  - pip
  - pip:
    - polartoolkit==0.6
  
